### PR TITLE
Abstract markup. Author info update.

### PR DESCRIPTION
**Pull request by rpgoldman**
Adds comments about rhetorical purpose in the abstract.

This commit has some minor fixes (like a better email address for me), but also has some comments about the rhetorical structure of the abstract.

The abstract suddenly pops in with a discussion of scripting, which isn't mentioned in the title, and isn't really carried through into an argument.  I'm inclined to think we're better off deferring discussion of CL for scripting to a separate paper.

### CODE REVIEW

**Comment by fare** [comment]
Are these comments intended to be part of the paper, or shouldn't they instead be part of a discussion such as here?

**Comment by rpgoldman** [comment]
Yes, they are editorial comments, and suggestions for how we might consider revising the current draft.

A word of explanation:

In my usual authoring process, my colleagues and I put comments in the paper, and then remove them as issues are dealt with.  That way you can simply work on the paper. I don't see a clear win to smearing editorial discussion all over the internet (i.e., some in github issues, some in source files, some in emails), as opposed to just keeping everything in the manuscript.  It's certainly not obvious to me that using trouble tickets is the way to go.

**Comment by fare** [comment]
Works for me, though I'd rather there be some macros to distinguish between remarks and text, and eliminate the remarks in one PDF output.

**Comment by rpgoldman** [comment]
If this was LaTeX, I would define `\elias`, `\rpg`, `\fare` commands for adding notes, and a boolean (`draftmode`).  Notes commands would expand to nothing when `draftmode = false`.  But that requires more scribble-fu than I have.

**Comment by fare** [comment]
I created a target `make ann` and a macro `@annotation{}`. You can easily define `@elias{}` `@fare{}` and `@rpg{}` if you wish.

**Comment by fare** [comment]
Also, you should have commit rights, so feel free to push modifications directly with suitable annotations.

**Comment by fare** [comment]
OK, I defined those macros, and added responses of my own. Let's continue the discussion there.

**Pull request closed without merging**
